# Service port
server:
  port: 8081
 # H2 database configuration
spring:
  datasource:
    url: jdbc:h2:mem:transactionshandlerdb
    #url: jdbc:h2:file:/home/raido/Dropbox/Programacion/Java/EntornosDeDesarrollo/data
    driverClassName: org.h2.Driver
    username: admin
    password:    
  h2:
    console:
      enabled: true
    # console URL: http://localhost:8081/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
